#!/bin/bash

key=~/keys/root

case $1 in
puppet) host='192.168.3.100';;
jenkins) host='192.168.3.35';;
sun) host='192.168.5.10';;
proxima) host='192.168.5.11';;
test) host='192.168.3.80';;
*) if [ ${#$1} -le 3 ]; then
        host="192.168.3.$1"
   else 
	host=$1
   fi;;
esac

ssh -i $key root@$host

